### ISSUE TITLE
Regarding the issue of excessive data size in RecExplainer.

### ISSUE THREAD

**Issue by WENG-gogo** [microsoft/RecAI#71]
Hello, I would like to ask why I always get the prompt "Token indices sequence length is longer than the specified maximum sequence length for this model (2636 > 1024). Running this sequence through the model will result in indexing errors" when running "recexplainer_data_pipeline.sh". This issue has been bothering me for several days.

**Comment by Micheallei** [comment]
This warning will not cause any problems when running "recexplainer_data_pipeline.sh". Because the sequence length used for training our model is 1024, so we truncate some cases that are too long during the data processing stage.

**Comment by WENG-gogo** [comment]
The translation of the provided Chinese text into English is: "Excuse me, in which Python file is sequence truncation implemented? The truncation is not working on my end.

**Comment by Micheallei** [comment]
Sorry for the late reply. Could you please provide the complete error message, including which line of the Python file caused the error?

**Comment by Micheallei** [comment]
In fact, the only problem here is "python: can't open file '/root/RecExplainer/preprocess/preprocess/gpt_api.py': [Errno 2] No such file or directory.".  The reason for this error is that gpt_api.py is actually in path '/root/RecExplainer/preprocess/gpt_api.py'.

Others like "Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained. Token indices sequence length is longer than the specified maximum sequence length for this model (2636 > 1024). Running this sequence through the model will result in indexing errors." are warnings that you don't need to worry about.

The problem will be fixed by [#77](https://github.com/microsoft/RecAI/pull/77).

In addition, we have unified the file paths in different scripts in this PR. You can refer to the Dataset Preparation for Target Recommender Model, Training and Inference with the Target Recommender Model, and Dataset Preparation for RecExplainer Model sections in the latest readme to reorganize your data files.

**Comment by WENG-gogo** [comment]
Here is the English translation of the provided text:

"Thank you very much for your reply, it was very helpful to me, and I successfully modified the path. This time, after I ran 'bash shell/recexplainer_data_pipeline.sh', I got an AttributeError: 'NoneType' object has no attribute 'startswith'. So I set the model to 'export MODEL=gpt-3'. But this time the error message is:"
Traceback (most recent call last):
  File "/root/miniconda3/envs/recexplainer/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 413, in get_loc
    return self._range.index(new_key)
ValueError: 9 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/RecExplainer/preprocess/amazon_generate_v3.py", line 209, in <module>
    gen_uid2text(user_items, meta_infos, args)
  File "/root/RecExplainer/preprocess/amazon_generate_v3.py", line 103, in gen_uid2text
    answer = query_profile.loc[uid-1, 'target']
  File "/root/miniconda3/envs/recexplainer/lib/python3.10/site-packages/pandas/core/indexing.py", line 1183, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/root/miniconda3/envs/recexplainer/lib/python3.10/site-packages/pandas/core/frame.py", line 4221, in _get_value
    row = self.index.get_loc(index)
  File "/root/miniconda3/envs/recexplainer/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 415, in get_loc
    raise KeyError(key) from err
KeyError: 9
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Token indices sequence length is longer than the specified maximum sequence length for this model (2636 > 1024). Running this sequence through the model will result in indexing errors。
train_uid2hist_intention: 10530, valid_uid2hist_intention: 391, train_uid2hist_both: 10530, valid_uid2hist_both: 391
Traceback (most recent call last):
  File "/root/miniconda3/envs/recexplainer/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 413, in get_loc
    return self._range.index(new_key)
ValueError: 9 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/RecExplainer/preprocess/mf_amazon_video_games_generate.py", line 210, in <module>
    gen_uid2text(user_items, meta_infos, args)
  File "/root/RecExplainer/preprocess/mf_amazon_video_games_generate.py", line 104, in gen_uid2text
    answer = query_profile.loc[uid-1, 'target']
  File "/root/miniconda3/envs/recexplainer/lib/python3.10/site-packages/pandas/core/indexing.py", line 1183, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/root/miniconda3/envs/recexplainer/lib/python3.10/site-packages/pandas/core/frame.py", line 4221, in _get_value
    row = self.index.get_loc(index)
  File "/root/miniconda3/envs/recexplainer/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 415, in get_loc
    raise KeyError(key) from err
KeyError: 9。
Is this still a matter of the data being too large? Is there a solution to this problem?

**Comment by Micheallei** [comment]
In fact, the uid2summary part uses gpt to generate a summary of the user history for each user. It seems that the reason for the error is that you did not generate all the data in `recexplainer_data_pipeline.sh` line 24-31, resulting in an index error when the subsequent script is run.
You can check the generated `$PROCESS_DATA_DIR/gpt4_data/test_response.csv` file to see if it is complete.

If you want to run the script without using gpt to generate data, you can comment out `amazon_generate_v3.py` line 91-112

**Comment by Micheallei** [comment]
If GPT is not used, the quality of generated explanations by the trained LLM may be relatively low, and the ability to summarize the preferences of user embeddings is insufficient.
Regarding the index out of range error you mentioned, based on the error message you gave earlier 
`File "/root/RecExplainer/preprocess/mf_amazon_video_games_generate.py", line 104, in gen_uid2text
answer = query_profile.loc[uid-1, 'target']`
If you have commented lines 91-112 in amazon_generate_v3.py out, you won't get this error.
I'm not sure what the error is now, you may need to check it further

**Comment by WENG-gogo** [comment]
Excuse me.Does RecExplainer require 8 GPUs? I couldn't run the model on a computer with only 1 GPU.

**Comment by Micheallei** [comment]
I think one 80GB A100 should be able to train? Refer to `RecExplainer/shell/train.sh`, change `--nproc_per_node 4` in `torchrun --nnodes=1 --nproc_per_node 4 --master_port=29501 ./src/sft_training.py` to `--nproc_per_node 1`.

**Comment by WENG-gogo** [comment]
I'm sorry, I commented out lines 91-112 of the amazon_generate_v3.py file. However, when I run "bash shell/recexplainer_data_pipeline.sh", the system still prompts with the following error:
Traceback (most recent call last):
  File "/root/miniconda3/envs/recexplainer/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 413, in get_loc
    return self._range.index(new_key)
ValueError: 9 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/RecExplainer/preprocess/mf_amazon_video_games_generate.py", line 210, in <module>
    gen_uid2text(user_items, meta_infos, args)
  File "/root/RecExplainer/preprocess/mf_amazon_video_games_generate.py", line 104, in gen_uid2text
    answer = query_profile.loc[uid-1, 'target']
  File "/root/miniconda3/envs/recexplainer/lib/python3.10/site-packages/pandas/core/indexing.py", line 1183, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/root/miniconda3/envs/recexplainer/lib/python3.10/site-packages/pandas/core/frame.py", line 4221, in _get_value
    row = self.index.get_loc(index)
  File "/root/miniconda3/envs/recexplainer/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 415, in get_loc
    raise KeyError(key) from err
KeyError: 9
获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: YuxuanLei ***@***.***>
发送时间: Friday, January 3, 2025 8:06:02 PM
收件人: microsoft/RecAI ***@***.***>
抄送: WENG-gogo ***@***.***>; Author ***@***.***>
主题: Re: [microsoft/RecAI] Regarding the issue of excessive data size in RecExplainer. (Issue #71)


I think one 80GB A100 should be able to train? Refer to RecExplainer/shell/train.sh, change --nproc_per_node 4 in torchrun --nnodes=1 --nproc_per_node 4 --master_port=29501 ./src/sft_training.py to --nproc_per_node 1.

―

**Comment by WENG-gogo** [comment]
**I'm sorry, I commented out lines 91-112 of the amazon_generate_v3.py file. However, when I run "bash shell/recexplainer_data_pipeline.sh", the system still prompts with the following error:**
Traceback (most recent call last):
  File "/root/miniconda3/envs/recexplainer/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 413, in get_loc
    return self._range.index(new_key)
ValueError: 9 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/RecExplainer/preprocess/mf_amazon_video_games_generate.py", line 210, in <module>
    gen_uid2text(user_items, meta_infos, args)
  File "/root/RecExplainer/preprocess/mf_amazon_video_games_generate.py", line 104, in gen_uid2text
    answer = query_profile.loc[uid-1, 'target']
  File "/root/miniconda3/envs/recexplainer/lib/python3.10/site-packages/pandas/core/indexing.py", line 1183, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/root/miniconda3/envs/recexplainer/lib/python3.10/site-packages/pandas/core/frame.py", line 4221, in _get_value
    row = self.index.get_loc(index)
  File "/root/miniconda3/envs/recexplainer/lib/python3.10/site-packages/pandas/core/indexes/range.py", line 415, in get_loc
    raise KeyError(key) from err
KeyError: 9

I don't know how to deal it,do I hava to use GPT?

**Comment by Micheallei** [comment]
You can look at the `RecExplainer/shell/recexplainer_data_pipeline.sh`, which generates training data for SASRec and MF models in turn. So the solution is to comment out lines 95-113 in `RecExplainer/preprocess/mf_amazon_video_games_generate.py` for not to use gpt when generating training data for MF model.
