### ISSUE TITLE
issue with reproducing the result with static data

### ISSUE THREAD

**Issue by tiebreaker4869** [microsoft/RecAI#73]
hello,
given the static dataset i try to run single_gpu_sft_train.sh but got the following errors at validation time:
```
Traceback (most recent call last):
  File "/root/RecAI-main/RecLM-gen/main.py", line 36, in <module>
    trainer.SFT_train()
  File "/root/RecAI-main/RecLM-gen/sft/trainer.py", line 119, in SFT_train
    val_loss = self.SFT_val_inference(epoch)
  File "/root/anaconda3/envs/reclm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/RecAI-main/RecLM-gen/utils/tools.py", line 197, in inner
    out = fn(self, *args, **kwargs)
  File "/root/RecAI-main/RecLM-gen/sft/trainer.py", line 188, in SFT_val_inference
    metrics_dict.add_sample(batch['task'][i], batch['input_field_data'][i], output_title_list[i], output_labels[i])
  File "/root/RecAI-main/RecLM-gen/utils/metrics.py", line 66, in add_sample
    if input_field_data['target_item_title'] in _output_titles:
KeyError: 'target_item_title'
  0%|                             
```

further inspect shows that:
```
            for i in range(bs):
                metrics_dict.add_sample(batch['task'][i], batch['input_field_data'][i], output_title_list[i], output_labels[i])
            pbar.update(1)
```

when further indexing batch['input_field_data'][i], there is no such key as: target_item_title, but only:

```
user', 'target_item', 'sub_sequential', 'history', 'target_category', 'item_count'
```

could you provide some fix or re-upload the valid data. thank you!

**Comment by Luuuk12321** [comment]
We had re-uploaded the new dataset in this [link](https://drive.google.com/file/d/1xmi91bJqATQzoaF_qRRc5nGILfnDaTga/view?usp=sharing).

**Comment by Research-novice996** [comment]
Hello Author, I couldn't find the steam_games.csv file while processing the dataset. Could you please tell me where to download this file?
